import "../styles/globals.scss";
import "../styles/fonts.scss";
import type {AppProps} from "next/app";
import NavControls from "../components/NavControls";
import Head from "next/head";

function MyApp({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <title>code-&gr;share</title>
            </Head>
            <NavControls>
                <Component {...pageProps} />
            </NavControls>
        </>
    )
}

export default MyApp;
