name: Trigger auto deployment for code-share-key-terms-extractor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/home/runner/work/code-share/code-share/key_terms_extractor/**'
    - '.github/workflows/code-share-key-terms-extractor-AutoDeployTrigger-91aaae88-fd28-4798-8968-c6bfd5c43d20.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CODESHAREKEYTERMSEXTRACTOR_REGISTRY_USERNAME }}
          password: ${{ secrets.CODESHAREKEYTERMSEXTRACTOR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cau777/code-share-key-terms-extractor:${{ github.sha }}
          file: /home/runner/work/code-share/code-share/key_terms_extractor/Dockerfile
          context: /home/runner/work/code-share/code-share/key_terms_extractor/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CODESHAREKEYTERMSEXTRACTOR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n code-share-key-terms-extractor -g code-share --server docker.io --username  ${{ secrets.CODESHAREKEYTERMSEXTRACTOR_REGISTRY_USERNAME }} --password ${{ secrets.CODESHAREKEYTERMSEXTRACTOR_REGISTRY_PASSWORD }}
            az containerapp update -n code-share-key-terms-extractor -g code-share --image cau777/code-share-key-terms-extractor:${{ github.sha }}
