name: Trigger auto deployment for code-share-nextjs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/home/runner/work/code-share/code-share/client/**'
    - '.github/workflows/code-share-nextjs-AutoDeployTrigger-ccef9931-c917-4e7a-8466-10f5c9739f12.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CODESHARENEXTJS_REGISTRY_USERNAME }}
          password: ${{ secrets.CODESHARENEXTJS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cau777/code-share-nextjs:${{ github.sha }}
          file: /home/runner/work/code-share/code-share/client/Dockerfile
          context: /home/runner/work/code-share/code-share/client/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CODESHARENEXTJS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n code-share-nextjs -g code-share --server docker.io --username  ${{ secrets.CODESHARENEXTJS_REGISTRY_USERNAME }} --password ${{ secrets.CODESHARENEXTJS_REGISTRY_PASSWORD }}
            az containerapp update -n code-share-nextjs -g code-share --image cau777/code-share-nextjs:${{ github.sha }}
