name: Docker Deploy image-service

on:
  # Allow manually trigger
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build image-service
        run: docker build -t cau777/code-share-image-service ./ImageService

      - name: Docker push
        run: docker push cau777/code-share-image-service:latest