name: Docker Deploy key-terms-extractor

on:
  # Allow manually trigger
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build key-terms-extractor
        run: docker build -t cau777/code-share-key-terms-extractor ./key_terms_extractor

      - name: Docker push
        run: docker push cau777/code-share-key-terms-extractor:latest