name: Docker Deploy nextjs

on:
  # Allow manually trigger
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build client
        run: docker build -t cau777/code-share-nextjs ./client

      - name: Docker push
        run: docker push cau777/code-share-nextjs:latest